### PR TITLE
This change makes the minecraftd.sh script slightly more generic, and allows cuberite to be launched from it.

### PR DESCRIPTION
**Pull request by cameroncros**
to launch cuberite with this script, do:
sudo GAME=cuberite NAME=cuberite ./minecraftd.sh start

### CODE REVIEW

**Comment by Edenhofer** [comment]
This is basically what I have tried (though I took a different approach, more like minecraftd.sh vs spigot.sh) but unfortunately it won't fix your problem! Cuberite just does not log the commands to the log file. However this script depends on being kept up to date through this mechanism.

**Comment by cameroncros** [comment]
My problem was only that I couldnt get to the console with the previous init script for cuberite. With this I can use it to get to the console. In terms of the commands being output to the log file, I dont have a solution there, aside from modifying cuberite to do that properly. Would you like me to investigate that?

**Comment by Edenhofer** [comment]
Sure, if you can spare the time. That was the main concern for porting the script.

**Comment by Edenhofer** [comment]
I added complete cuberite support to the script in a recent commit ada9f59:

> - Handle server command output completely through screen instead of relying
>   on a possible outdated log file. (Implemented in the game_command function.)
>   The default screen command dump resides in /tmp.
> - LOGPATH is not needed anymore.
> - Unite various java options into one lengthier SERVER_START_CMD.
> - Update configuration file accordingly.

Not only is it now possible to attach to the console but rather all features from the minecraft-server are available for cuberite: backup, restore, idle_server, single command execution and proper systemd support.

I turned away from solely relying on the log file and chose to better integrate GNU screen since cuberite apparently [logs only in 4 KiB blocks](https://github.com/cuberite/cuberite/pull/2420) to reduce the system footprint and neither did I wanted to circumvent this optimization nor did I wanted to drop the feature.

**Pull request closed without merging**
