### PR TITLE
Update minecraft-server to 1.17.1

### PR DESCRIPTION
**Pull request by nick-dumas**

### CODE REVIEW

**Comment by Edenhofer** [comment]
Thanks for the merge request. I was hoping to get #10 merged before 1.17.1 but depending on how long this is going to take, I might need to update before that.

**Comment by nick-dumas** [comment]
No worries, just did the update and thought I'd share the diff

**Comment by Edenhofer** [comment]
Thanks! It certainly is appreciated.

**Comment by Edenhofer** [comment]
Ok, just updated regardless. I will rebase the tmux stuff.

**Pull request closed without merging**
